package com.company.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-15T19:12:17.435+03:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://api.company.com/", name = "ProjectWebServiceEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectWebServiceEndpoint {

    @WebMethod
    @Action(input = "http://api.company.com/ProjectWebServiceEndpoint/removeByNameRequest", output = "http://api.company.com/ProjectWebServiceEndpoint/removeByNameResponse")
    @RequestWrapper(localName = "removeByName", targetNamespace = "http://api.company.com/", className = "com.company.api.RemoveByName")
    @ResponseWrapper(localName = "removeByNameResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.RemoveByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.company.api.Session arg1
    );

    @WebMethod
    @Action(input = "http://api.company.com/ProjectWebServiceEndpoint/getListRequest", output = "http://api.company.com/ProjectWebServiceEndpoint/getListResponse")
    @RequestWrapper(localName = "getList", targetNamespace = "http://api.company.com/", className = "com.company.api.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.GetListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.company.api.Project> getList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.company.api.Session arg0
    );

    @WebMethod
    @Action(input = "http://api.company.com/ProjectWebServiceEndpoint/findByIdRequest", output = "http://api.company.com/ProjectWebServiceEndpoint/findByIdResponse")
    @RequestWrapper(localName = "findById", targetNamespace = "http://api.company.com/", className = "com.company.api.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.company.api.Project findById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.company.api.Session arg1
    );

    @WebMethod
    @Action(input = "http://api.company.com/ProjectWebServiceEndpoint/saveRequest", output = "http://api.company.com/ProjectWebServiceEndpoint/saveResponse")
    @RequestWrapper(localName = "save", targetNamespace = "http://api.company.com/", className = "com.company.api.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean save(
        @WebParam(name = "arg0", targetNamespace = "")
        com.company.api.Project arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.company.api.Session arg1
    );

    @WebMethod
    @Action(input = "http://api.company.com/ProjectWebServiceEndpoint/updateRequest", output = "http://api.company.com/ProjectWebServiceEndpoint/updateResponse")
    @RequestWrapper(localName = "update", targetNamespace = "http://api.company.com/", className = "com.company.api.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.UpdateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        com.company.api.Project arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.company.api.Session arg1
    );

    @WebMethod
    @Action(input = "http://api.company.com/ProjectWebServiceEndpoint/findByNameRequest", output = "http://api.company.com/ProjectWebServiceEndpoint/findByNameResponse")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.company.api.Project findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.company.api.Session arg1
    );
}
