package com.company.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-01T11:46:30.837+03:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://api.company.com/", name = "TaskWebServiceEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskWebServiceEndpoint {

    @WebMethod
    @Action(input = "http://api.company.com/TaskWebServiceEndpoint/updateTaskRequest", output = "http://api.company.com/TaskWebServiceEndpoint/updateTaskResponse")
    @RequestWrapper(localName = "updateTask", targetNamespace = "http://api.company.com/", className = "com.company.api.UpdateTask")
    @ResponseWrapper(localName = "updateTaskResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.UpdateTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.company.api.TaskDTO updateTask(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "newName", targetNamespace = "")
        java.lang.String newName,
        @WebParam(name = "newDescription", targetNamespace = "")
        java.lang.String newDescription,
        @WebParam(name = "newNameProject", targetNamespace = "")
        java.lang.String newNameProject,
        @WebParam(name = "session", targetNamespace = "")
        com.company.api.Session session
    );

    @WebMethod
    @Action(input = "http://api.company.com/TaskWebServiceEndpoint/removeByNameTaskRequest", output = "http://api.company.com/TaskWebServiceEndpoint/removeByNameTaskResponse")
    @RequestWrapper(localName = "removeByNameTask", targetNamespace = "http://api.company.com/", className = "com.company.api.RemoveByNameTask")
    @ResponseWrapper(localName = "removeByNameTaskResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.RemoveByNameTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean removeByNameTask(
        @WebParam(name = "task_name", targetNamespace = "")
        java.lang.String taskName,
        @WebParam(name = "session", targetNamespace = "")
        com.company.api.Session session
    );

    @WebMethod
    @Action(input = "http://api.company.com/TaskWebServiceEndpoint/getListTaskRequest", output = "http://api.company.com/TaskWebServiceEndpoint/getListTaskResponse")
    @RequestWrapper(localName = "getListTask", targetNamespace = "http://api.company.com/", className = "com.company.api.GetListTask")
    @ResponseWrapper(localName = "getListTaskResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.GetListTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.company.api.TaskDTO> getListTask(
        @WebParam(name = "session", targetNamespace = "")
        com.company.api.Session session
    );

    @WebMethod
    @Action(input = "http://api.company.com/TaskWebServiceEndpoint/saveTaskRequest", output = "http://api.company.com/TaskWebServiceEndpoint/saveTaskResponse")
    @RequestWrapper(localName = "saveTask", targetNamespace = "http://api.company.com/", className = "com.company.api.SaveTask")
    @ResponseWrapper(localName = "saveTaskResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.SaveTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.company.api.TaskDTO saveTask(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "description", targetNamespace = "")
        java.lang.String description,
        @WebParam(name = "nameProject", targetNamespace = "")
        java.lang.String nameProject,
        @WebParam(name = "session", targetNamespace = "")
        com.company.api.Session session
    );

    @WebMethod
    @Action(input = "http://api.company.com/TaskWebServiceEndpoint/findByIdTaskRequest", output = "http://api.company.com/TaskWebServiceEndpoint/findByIdTaskResponse")
    @RequestWrapper(localName = "findByIdTask", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByIdTask")
    @ResponseWrapper(localName = "findByIdTaskResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByIdTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.company.api.TaskDTO findByIdTask(
        @WebParam(name = "task_id", targetNamespace = "")
        java.lang.String taskId,
        @WebParam(name = "session", targetNamespace = "")
        com.company.api.Session session
    );

    @WebMethod
    @Action(input = "http://api.company.com/TaskWebServiceEndpoint/findByNameTaskRequest", output = "http://api.company.com/TaskWebServiceEndpoint/findByNameTaskResponse")
    @RequestWrapper(localName = "findByNameTask", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByNameTask")
    @ResponseWrapper(localName = "findByNameTaskResponse", targetNamespace = "http://api.company.com/", className = "com.company.api.FindByNameTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.company.api.TaskDTO findByNameTask(
        @WebParam(name = "task_name", targetNamespace = "")
        java.lang.String taskName,
        @WebParam(name = "session", targetNamespace = "")
        com.company.api.Session session
    );
}
