package com.company.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.company.api.TaskWebServiceEndpoint;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-01T11:46:30.853+03:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "TaskWebServiceEndpointImplService",
                  wsdlLocation = "http://localhost:1987/wss/task?wsdl",
                  targetNamespace = "http://endpoint.company.com/")
public class TaskWebServiceEndpointImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.company.com/", "TaskWebServiceEndpointImplService");
    public final static QName TaskWebServiceEndpointImplPort = new QName("http://endpoint.company.com/", "TaskWebServiceEndpointImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1987/wss/task?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaskWebServiceEndpointImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:1987/wss/task?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaskWebServiceEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskWebServiceEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskWebServiceEndpointImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaskWebServiceEndpointImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaskWebServiceEndpointImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaskWebServiceEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TaskWebServiceEndpoint
     */
    @WebEndpoint(name = "TaskWebServiceEndpointImplPort")
    public TaskWebServiceEndpoint getTaskWebServiceEndpointImplPort() {
        return super.getPort(TaskWebServiceEndpointImplPort, TaskWebServiceEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskWebServiceEndpoint
     */
    @WebEndpoint(name = "TaskWebServiceEndpointImplPort")
    public TaskWebServiceEndpoint getTaskWebServiceEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(TaskWebServiceEndpointImplPort, TaskWebServiceEndpoint.class, features);
    }

}
