package com.company.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.company.api.TaskWebServiceEndpoint;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-15T19:12:17.351+03:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "TaskProjectWebServiceEndpointImplService",
                  wsdlLocation = "http://localhost:1986/wss/task?wsdl",
                  targetNamespace = "http://endpoint.company.com/")
public class TaskProjectWebServiceEndpointImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.company.com/", "TaskProjectWebServiceEndpointImplService");
    public final static QName TaskProjectWebServiceEndpointImplPort = new QName("http://endpoint.company.com/", "TaskProjectWebServiceEndpointImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:1986/wss/task?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaskProjectWebServiceEndpointImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:1986/wss/task?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaskProjectWebServiceEndpointImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskProjectWebServiceEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskProjectWebServiceEndpointImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaskProjectWebServiceEndpointImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaskProjectWebServiceEndpointImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaskProjectWebServiceEndpointImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TaskWebServiceEndpoint
     */
    @WebEndpoint(name = "TaskProjectWebServiceEndpointImplPort")
    public TaskWebServiceEndpoint getTaskProjectWebServiceEndpointImplPort() {
        return super.getPort(TaskProjectWebServiceEndpointImplPort, TaskWebServiceEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskWebServiceEndpoint
     */
    @WebEndpoint(name = "TaskProjectWebServiceEndpointImplPort")
    public TaskWebServiceEndpoint getTaskProjectWebServiceEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(TaskProjectWebServiceEndpointImplPort, TaskWebServiceEndpoint.class, features);
    }

}
